/**
 * Landmarks, parks and natural places around the world that new workspaces are named after.
 * Each is a valid folder and branch name as written.
 */
export const LANDMARKS = [
  // Africa
  'kilimanjaro',
  'serengeti',
  'victoria-falls',
  'table-mountain',
  'okavango',
  'sahara',
  'namib',
  'ngorongoro',
  'atlas',
  'kruger',
  'sossusvlei',
  'zanzibar',
  'giza',
  'luxor',
  'masai-mara',
  'drakensberg',
  'lake-malawi',
  'bwindi',
  // Asia
  'fuji',
  'everest',
  'annapurna',
  'ha-long',
  'angkor',
  'borobudur',
  'komodo',
  'zhangjiajie',
  'guilin',
  'jiuzhaigou',
  'kyoto',
  'nara',
  'yakushima',
  'petra',
  'wadi-rum',
  'cappadocia',
  'pamukkale',
  'bagan',
  'phi-phi',
  'palawan',
  'baikal',
  'kamchatka',
  'altai',
  'ladakh',
  'hampi',
  'kerala',
  'sigiriya',
  'jeju',
  'seoraksan',
  'taroko',
  'socotra',
  // Europe
  'dolomites',
  'matterhorn',
  'mont-blanc',
  'jungfrau',
  'eiger',
  'plitvice',
  'cinque-terre',
  'amalfi',
  'santorini',
  'meteora',
  'olympus',
  'geirangerfjord',
  'lofoten',
  'preikestolen',
  'thingvellir',
  'vatnajokull',
  'skye',
  'snowdonia',
  'giants-causeway',
  'cliffs-of-moher',
  'connemara',
  'cairngorms',
  'stonehenge',
  'tatra',
  'carpathians',
  'black-forest',
  'saxon-switzerland',
  'camargue',
  'verdon',
  'picos',
  'teide',
  'alhambra',
  'douro',
  'azores',
  'madeira',
  'durmitor',
  // North America
  'yosemite',
  'yellowstone',
  'grand-canyon',
  'zion',
  'arches',
  'bryce',
  'sequoia',
  'redwood',
  'denali',
  'glacier',
  'acadia',
  'olympic',
  'rainier',
  'shasta',
  'tahoe',
  'big-sur',
  'joshua-tree',
  'death-valley',
  'everglades',
  'smoky',
  'teton',
  'banff',
  'jasper',
  'yoho',
  'louise',
  'tofino',
  'gros-morne',
  'niagara',
  'tulum',
  'copper-canyon',
  'monteverde',
  'arenal',
  'tikal',
  // South America
  'patagonia',
  'torres-del-paine',
  'fitz-roy',
  'perito-moreno',
  'iguazu',
  'machu-picchu',
  'titicaca',
  'uyuni',
  'atacama',
  'galapagos',
  'amazon',
  'pantanal',
  'angel-falls',
  'roraima',
  'lencois',
  'chapada',
  'aconcagua',
  'cotopaxi',
  // Oceania
  'uluru',
  'kakadu',
  'daintree',
  'great-barrier',
  'whitsunday',
  'blue-mountains',
  'cradle-mountain',
  'freycinet',
  'kimberley',
  'milford',
  'aoraki',
  'tongariro',
  'abel-tasman',
  'fiordland',
  'rotorua',
  'bora-bora',
  'moorea',
  // Antarctica and the Arctic
  'erebus',
  'svalbard',
  'ilulissat',
] as const;

/** A landmark's name as shown: `machu-picchu` reads as "Machu Picchu". */
export function landmarkLabel(name: string) {
  return name
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/**
 * A landmark no workspace has yet, picked at random so names don't run in an order. Once
 * every landmark is taken, they come round again with a number.
 */
export function landmarkName(taken: ReadonlySet<string>, random = Math.random) {
  for (let round = 1; ; round++) {
    const free = LANDMARKS.map((name) =>
      round === 1 ? name : `${name}-${round}`,
    ).filter((name) => !taken.has(name));
    if (free.length) return free[Math.floor(random() * free.length)];
  }
}
